# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '知识与参数.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(960, 771)
        self.gridLayout_2 = QtWidgets.QGridLayout(Frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Frame)
        self.tabWidget.setObjectName("tabWidget")
        self.system = QtWidgets.QWidget()
        self.system.setObjectName("system")
        self.sys_all = QtWidgets.QListWidget(self.system)
        self.sys_all.setGeometry(QtCore.QRect(490, 80, 411, 192))
        self.sys_all.setObjectName("sys_all")
        self.sys_comboBox_name = QtWidgets.QComboBox(self.system)
        self.sys_comboBox_name.setGeometry(QtCore.QRect(100, 80, 111, 31))
        self.sys_comboBox_name.setObjectName("sys_comboBox_name")
        self.sys_comboBox_name.addItem("")
        self.sys_comboBox_name.addItem("")
        self.sys_comboBox_name.addItem("")
        self.sys_lable_name = QtWidgets.QLabel(self.system)
        self.sys_lable_name.setGeometry(QtCore.QRect(40, 80, 51, 21))
        self.sys_lable_name.setObjectName("sys_lable_name")
        self.sys_lable_value = QtWidgets.QLabel(self.system)
        self.sys_lable_value.setGeometry(QtCore.QRect(250, 80, 51, 21))
        self.sys_lable_value.setObjectName("sys_lable_value")
        self.sys_lineEdit_value = QtWidgets.QLineEdit(self.system)
        self.sys_lineEdit_value.setGeometry(QtCore.QRect(310, 80, 113, 20))
        self.sys_lineEdit_value.setObjectName("sys_lineEdit_value")
        self.sys_add = QtWidgets.QPushButton(self.system)
        self.sys_add.setGeometry(QtCore.QRect(360, 140, 75, 23))
        self.sys_add.setObjectName("sys_add")
        self.sys_textBrowser = QtWidgets.QTextBrowser(self.system)
        self.sys_textBrowser.setGeometry(QtCore.QRect(90, 370, 791, 301))
        self.sys_textBrowser.setObjectName("sys_textBrowser")
        self.sys_lable_model = QtWidgets.QLabel(self.system)
        self.sys_lable_model.setGeometry(QtCore.QRect(30, 370, 61, 21))
        self.sys_lable_model.setObjectName("sys_lable_model")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/resources/button-2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.system, icon, "")
        self.model = QtWidgets.QWidget()
        self.model.setObjectName("model")
        self.model_add = QtWidgets.QPushButton(self.model)
        self.model_add.setGeometry(QtCore.QRect(350, 140, 75, 23))
        self.model_add.setObjectName("model_add")
        self.model_comboBox_type = QtWidgets.QComboBox(self.model)
        self.model_comboBox_type.setGeometry(QtCore.QRect(250, 70, 91, 21))
        self.model_comboBox_type.setObjectName("model_comboBox_type")
        self.model_comboBox_type.addItem("")
        self.model_comboBox_type.addItem("")
        self.model_comboBox_type.addItem("")
        self.model_textBrowser = QtWidgets.QTextBrowser(self.model)
        self.model_textBrowser.setGeometry(QtCore.QRect(130, 360, 791, 301))
        self.model_textBrowser.setObjectName("model_textBrowser")
        self.model_lineEdit_name = QtWidgets.QLineEdit(self.model)
        self.model_lineEdit_name.setGeometry(QtCore.QRect(60, 70, 113, 20))
        self.model_lineEdit_name.setObjectName("model_lineEdit_name")
        self.model_label_model = QtWidgets.QLabel(self.model)
        self.model_label_model.setGeometry(QtCore.QRect(10, 360, 101, 21))
        self.model_label_model.setObjectName("model_label_model")
        self.model_all = QtWidgets.QListWidget(self.model)
        self.model_all.setGeometry(QtCore.QRect(490, 70, 411, 192))
        self.model_all.setObjectName("model_all")
        self.model_name = QtWidgets.QLabel(self.model)
        self.model_name.setGeometry(QtCore.QRect(10, 70, 51, 21))
        self.model_name.setObjectName("model_name")
        self.model_label_type = QtWidgets.QLabel(self.model)
        self.model_label_type.setGeometry(QtCore.QRect(190, 70, 61, 21))
        self.model_label_type.setObjectName("model_label_type")
        self.model_label_default = QtWidgets.QLabel(self.model)
        self.model_label_default.setGeometry(QtCore.QRect(190, 110, 61, 21))
        self.model_label_default.setObjectName("model_label_default")
        self.model_lineEdit_default = QtWidgets.QLineEdit(self.model)
        self.model_lineEdit_default.setGeometry(QtCore.QRect(250, 110, 113, 20))
        self.model_lineEdit_default.setObjectName("model_lineEdit_default")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/resources/button-5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.model, icon1, "")
        self.state = QtWidgets.QWidget()
        self.state.setObjectName("state")
        self.state_add_class = QtWidgets.QPushButton(self.state)
        self.state_add_class.setGeometry(QtCore.QRect(320, 130, 75, 23))
        self.state_add_class.setObjectName("state_add_class")
        self.state_comboBox_kge = QtWidgets.QComboBox(self.state)
        self.state_comboBox_kge.setGeometry(QtCore.QRect(300, 60, 91, 31))
        self.state_comboBox_kge.setObjectName("state_comboBox_kge")
        self.state_textBrowser = QtWidgets.QTextBrowser(self.state)
        self.state_textBrowser.setGeometry(QtCore.QRect(110, 520, 791, 191))
        self.state_textBrowser.setObjectName("state_textBrowser")
        self.state_lineEdit_classname = QtWidgets.QLineEdit(self.state)
        self.state_lineEdit_classname.setGeometry(QtCore.QRect(100, 60, 113, 20))
        self.state_lineEdit_classname.setText("")
        self.state_lineEdit_classname.setObjectName("state_lineEdit_classname")
        self.label_6 = QtWidgets.QLabel(self.state)
        self.label_6.setGeometry(QtCore.QRect(10, 520, 91, 21))
        self.label_6.setObjectName("label_6")
        self.state_all_class = QtWidgets.QListWidget(self.state)
        self.state_all_class.setGeometry(QtCore.QRect(470, 60, 411, 192))
        self.state_all_class.setObjectName("state_all_class")
        self.label_7 = QtWidgets.QLabel(self.state)
        self.label_7.setGeometry(QtCore.QRect(20, 20, 131, 21))
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(self.state)
        self.label_9.setGeometry(QtCore.QRect(230, 60, 51, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.state)
        self.label_10.setGeometry(QtCore.QRect(20, 210, 111, 21))
        self.label_10.setObjectName("label_10")
        self.state_all = QtWidgets.QListWidget(self.state)
        self.state_all.setGeometry(QtCore.QRect(470, 280, 411, 192))
        self.state_all.setObjectName("state_all")
        item = QtWidgets.QListWidgetItem()
        self.state_all.addItem(item)
        self.state_comboBox_Class = QtWidgets.QComboBox(self.state)
        self.state_comboBox_Class.setGeometry(QtCore.QRect(250, 240, 121, 21))
        self.state_comboBox_Class.setObjectName("state_comboBox_Class")
        self.state_add = QtWidgets.QPushButton(self.state)
        self.state_add.setGeometry(QtCore.QRect(320, 450, 75, 23))
        self.state_add.setObjectName("state_add")
        self.label_12 = QtWidgets.QLabel(self.state)
        self.label_12.setGeometry(QtCore.QRect(20, 60, 81, 21))
        self.label_12.setObjectName("label_12")
        self.state_lineEdit_name = QtWidgets.QLineEdit(self.state)
        self.state_lineEdit_name.setGeometry(QtCore.QRect(90, 240, 61, 20))
        self.state_lineEdit_name.setText("")
        self.state_lineEdit_name.setObjectName("state_lineEdit_name")
        self.label_17 = QtWidgets.QLabel(self.state)
        self.label_17.setGeometry(QtCore.QRect(30, 240, 51, 21))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.state)
        self.label_18.setGeometry(QtCore.QRect(180, 240, 61, 21))
        self.label_18.setObjectName("label_18")
        self.checkBox = QtWidgets.QCheckBox(self.state)
        self.checkBox.setGeometry(QtCore.QRect(180, 450, 121, 16))
        self.checkBox.setObjectName("checkBox")
        self.layoutWidget = QtWidgets.QWidget(self.state)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 290, 371, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_value2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_value2.setObjectName("label_value2")
        self.gridLayout_3.addWidget(self.label_value2, 1, 5, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_3.addWidget(self.lineEdit_2, 1, 6, 1, 1)
        self.label_value1 = QtWidgets.QLabel(self.layoutWidget)
        self.label_value1.setObjectName("label_value1")
        self.gridLayout_3.addWidget(self.label_value1, 0, 5, 1, 1)
        self.label_slot2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_slot2.setObjectName("label_slot2")
        self.gridLayout_3.addWidget(self.label_slot2, 1, 3, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout_3.addWidget(self.comboBox_2, 1, 4, 1, 1)
        self.lineEdit_1 = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_1.sizePolicy().hasHeightForWidth())
        self.lineEdit_1.setSizePolicy(sizePolicy)
        self.lineEdit_1.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_1.setText("")
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.gridLayout_3.addWidget(self.lineEdit_1, 0, 6, 1, 1)
        self.label_slot1 = QtWidgets.QLabel(self.layoutWidget)
        self.label_slot1.setObjectName("label_slot1")
        self.gridLayout_3.addWidget(self.label_slot1, 0, 3, 1, 1)
        self.comboBox_1 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_1.setObjectName("comboBox_1")
        self.gridLayout_3.addWidget(self.comboBox_1, 0, 4, 1, 1)
        self.state_minus = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.state_minus.sizePolicy().hasHeightForWidth())
        self.state_minus.setSizePolicy(sizePolicy)
        self.state_minus.setMaximumSize(QtCore.QSize(30, 16777215))
        self.state_minus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.state_minus.setObjectName("state_minus")
        self.gridLayout_3.addWidget(self.state_minus, 1, 1, 1, 1)
        self.state_plus = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.state_plus.sizePolicy().hasHeightForWidth())
        self.state_plus.setSizePolicy(sizePolicy)
        self.state_plus.setMaximumSize(QtCore.QSize(30, 16777215))
        self.state_plus.setSizeIncrement(QtCore.QSize(20, 0))
        self.state_plus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.state_plus.setObjectName("state_plus")
        self.gridLayout_3.addWidget(self.state_plus, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 2, 1, 1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/resources/button-3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.state, icon2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Frame)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.sys_comboBox_name.setItemText(0, _translate("Frame", "esc"))
        self.sys_comboBox_name.setItemText(1, _translate("Frame", "if"))
        self.sys_comboBox_name.setItemText(2, _translate("Frame", "trace-detail"))
        self.sys_lable_name.setText(_translate("Frame", "参数名"))
        self.sys_lable_value.setText(_translate("Frame", "参数值"))
        self.sys_add.setText(_translate("Frame", "增加"))
        self.sys_textBrowser.setHtml(_translate("Frame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.sys_lable_model.setText(_translate("Frame", "模型预览"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.system), _translate("Frame", "系统参数"))
        self.model_add.setText(_translate("Frame", "增加"))
        self.model_comboBox_type.setItemText(0, _translate("Frame", "整数"))
        self.model_comboBox_type.setItemText(1, _translate("Frame", "浮点数"))
        self.model_comboBox_type.setItemText(2, _translate("Frame", "字符串"))
        self.model_textBrowser.setHtml(_translate("Frame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.model_label_model.setText(_translate("Frame", "模型参数预览"))
        self.model_name.setText(_translate("Frame", "参数名"))
        self.model_label_type.setText(_translate("Frame", "参数类型"))
        self.model_label_default.setText(_translate("Frame", "缺省值"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.model), _translate("Frame", "模型参数"))
        self.state_add_class.setText(_translate("Frame", "增加"))
        self.state_textBrowser.setHtml(_translate("Frame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_6.setText(_translate("Frame", "陈述知识预览"))
        self.label_7.setText(_translate("Frame", "陈述知识类定义"))
        self.label_9.setText(_translate("Frame", "知识槽"))
        self.label_10.setText(_translate("Frame", "陈述知识定义"))
        __sortingEnabled = self.state_all.isSortingEnabled()
        self.state_all.setSortingEnabled(False)
        item = self.state_all.item(0)
        item.setText(_translate("Frame", "知识名         知识类                     知识槽                                  ..."))
        self.state_all.setSortingEnabled(__sortingEnabled)
        self.state_add.setText(_translate("Frame", "增加"))
        self.label_12.setText(_translate("Frame", "知识类名称"))
        self.label_17.setText(_translate("Frame", "知识名"))
        self.label_18.setText(_translate("Frame", "知识类"))
        self.checkBox.setText(_translate("Frame", "初始知识"))
        self.label_value2.setText(_translate("Frame", "值"))
        self.label_value1.setText(_translate("Frame", "值"))
        self.label_slot2.setText(_translate("Frame", "槽"))
        self.label_slot1.setText(_translate("Frame", "槽"))
        self.state_minus.setText(_translate("Frame", "-"))
        self.state_plus.setText(_translate("Frame", "+"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.state), _translate("Frame", "陈述知识"))
import resources_rc
