# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '认知建模.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
sys.path.append('../样式/')
sys.path.append('样式/')

class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(934, 781)
        self.gridLayout_2 = QtWidgets.QGridLayout(Frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Frame)
        self.tabWidget.setObjectName("tabWidget")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        self.pushButton_6.setGeometry(QtCore.QRect(60, 660, 75, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.textEdit = QtWidgets.QTextEdit(self.widget)
        self.textEdit.setGeometry(QtCore.QRect(30, 70, 831, 551))
        self.textEdit.setObjectName("textEdit")
        self.label_16 = QtWidgets.QLabel(self.widget)
        self.label_16.setGeometry(QtCore.QRect(30, 40, 81, 21))
        self.label_16.setObjectName("label_16")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/resources/button-2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.widget, icon, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.pushButton = QtWidgets.QPushButton(self.tab_3)
        self.pushButton.setGeometry(QtCore.QRect(50, 80, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(50, 50, 241, 16))
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_3)
        self.textBrowser.setGeometry(QtCore.QRect(50, 120, 791, 571))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 80, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_3.setGeometry(QtCore.QRect(220, 80, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_4.setGeometry(QtCore.QRect(310, 80, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/resources/button-3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_3, icon1, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_5 = QtWidgets.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(450, 30, 41, 21))
        self.label_5.setObjectName("label_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_6.setGeometry(QtCore.QRect(500, 30, 113, 20))
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_24 = QtWidgets.QLabel(self.tab_4)
        self.label_24.setGeometry(QtCore.QRect(40, 30, 91, 21))
        self.label_24.setObjectName("label_24")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_5.setGeometry(QtCore.QRect(770, 630, 75, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.textBrowser_5 = QtWidgets.QTextBrowser(self.tab_4)
        self.textBrowser_5.setGeometry(QtCore.QRect(470, 410, 381, 191))
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.comboBox_14 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_14.setGeometry(QtCore.QRect(500, 110, 31, 21))
        self.comboBox_14.setObjectName("comboBox_14")
        self.comboBox_15 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_15.setGeometry(QtCore.QRect(650, 200, 91, 21))
        self.comboBox_15.setObjectName("comboBox_15")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_15.addItem("")
        self.comboBox_16 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_16.setGeometry(QtCore.QRect(650, 170, 91, 21))
        self.comboBox_16.setObjectName("comboBox_16")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_16.addItem("")
        self.comboBox_17 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_17.setGeometry(QtCore.QRect(540, 170, 91, 21))
        self.comboBox_17.setObjectName("comboBox_17")
        self.comboBox_17.addItem("")
        self.comboBox_17.addItem("")
        self.comboBox_18 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_18.setGeometry(QtCore.QRect(540, 200, 91, 21))
        self.comboBox_18.setObjectName("comboBox_18")
        self.comboBox_18.addItem("")
        self.label_11 = QtWidgets.QLabel(self.tab_4)
        self.label_11.setGeometry(QtCore.QRect(450, 170, 71, 21))
        self.label_11.setObjectName("label_11")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_7.setGeometry(QtCore.QRect(760, 200, 111, 20))
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_10.setGeometry(QtCore.QRect(760, 110, 113, 20))
        self.lineEdit_10.setText("")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_11.setGeometry(QtCore.QRect(760, 70, 113, 20))
        self.lineEdit_11.setText("")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.comboBox_19 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_19.setGeometry(QtCore.QRect(540, 230, 91, 21))
        self.comboBox_19.setObjectName("comboBox_19")
        self.comboBox_19.addItem("")
        self.label_13 = QtWidgets.QLabel(self.tab_4)
        self.label_13.setGeometry(QtCore.QRect(450, 70, 71, 21))
        self.label_13.setObjectName("label_13")
        self.comboBox_20 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_20.setGeometry(QtCore.QRect(540, 110, 91, 21))
        self.comboBox_20.setObjectName("comboBox_20")
        self.comboBox_20.addItem("")
        self.comboBox_21 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_21.setGeometry(QtCore.QRect(540, 70, 91, 21))
        self.comboBox_21.setObjectName("comboBox_21")
        self.comboBox_21.addItem("")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_12.setGeometry(QtCore.QRect(760, 230, 111, 20))
        self.lineEdit_12.setText("")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.comboBox_22 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_22.setGeometry(QtCore.QRect(650, 230, 91, 21))
        self.comboBox_22.setObjectName("comboBox_22")
        self.comboBox_22.addItem("")
        self.comboBox_23 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_23.setGeometry(QtCore.QRect(650, 70, 91, 21))
        self.comboBox_23.setObjectName("comboBox_23")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.comboBox_23.addItem("")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_13.setGeometry(QtCore.QRect(760, 170, 113, 20))
        self.lineEdit_13.setText("")
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.comboBox_24 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_24.setGeometry(QtCore.QRect(650, 110, 91, 21))
        self.comboBox_24.setObjectName("comboBox_24")
        self.comboBox_24.addItem("")
        self.label_27 = QtWidgets.QLabel(self.tab_4)
        self.label_27.setGeometry(QtCore.QRect(450, 370, 91, 21))
        self.label_27.setObjectName("label_27")
        self.listWidget_6 = QtWidgets.QListWidget(self.tab_4)
        self.listWidget_6.setGeometry(QtCore.QRect(40, 410, 411, 251))
        self.listWidget_6.setObjectName("listWidget_6")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_6.addItem(item)
        self.label_28 = QtWidgets.QLabel(self.tab_4)
        self.label_28.setGeometry(QtCore.QRect(40, 120, 91, 21))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.tab_4)
        self.label_29.setGeometry(QtCore.QRect(40, 220, 91, 21))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.tab_4)
        self.label_30.setGeometry(QtCore.QRect(40, 380, 91, 21))
        self.label_30.setObjectName("label_30")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_7.setGeometry(QtCore.QRect(430, 110, 21, 21))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_8.setGeometry(QtCore.QRect(460, 110, 21, 21))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_9.setGeometry(QtCore.QRect(500, 230, 21, 21))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_10.setGeometry(QtCore.QRect(470, 230, 21, 21))
        self.pushButton_10.setObjectName("pushButton_10")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/resources/button-5.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_4, icon2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Frame)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.pushButton_6.setText(_translate("Frame", "模型检查"))
        self.textEdit.setHtml(_translate("Frame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_16.setText(_translate("Frame", "认知模型"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.widget), _translate("Frame", "模型预览"))
        self.pushButton.setText(_translate("Frame", "Run"))
        self.label.setText(_translate("Frame", "Model Name:Three position"))
        self.pushButton_2.setText(_translate("Frame", "Pause"))
        self.pushButton_3.setText(_translate("Frame", "Clear"))
        self.pushButton_4.setText(_translate("Frame", "Restart"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Frame", "模型运行"))
        self.label_5.setText(_translate("Frame", "时间"))
        self.label_24.setText(_translate("Frame", "系统参数"))
        self.pushButton_5.setText(_translate("Frame", "保存"))
        self.textBrowser_5.setHtml(_translate("Frame", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.comboBox_15.setItemText(0, _translate("Frame", "IS"))
        self.comboBox_15.setItemText(1, _translate("Frame", "="))
        self.comboBox_15.setItemText(2, _translate("Frame", ">"))
        self.comboBox_15.setItemText(3, _translate("Frame", "<"))
        self.comboBox_15.setItemText(4, _translate("Frame", ">="))
        self.comboBox_15.setItemText(5, _translate("Frame", "<="))
        self.comboBox_16.setItemText(0, _translate("Frame", "count"))
        self.comboBox_16.setItemText(1, _translate("Frame", "="))
        self.comboBox_16.setItemText(2, _translate("Frame", ">"))
        self.comboBox_16.setItemText(3, _translate("Frame", "<"))
        self.comboBox_16.setItemText(4, _translate("Frame", ">="))
        self.comboBox_16.setItemText(5, _translate("Frame", "<="))
        self.comboBox_17.setItemText(0, _translate("Frame", "goal"))
        self.comboBox_17.setItemText(1, _translate("Frame", "count-order"))
        self.comboBox_18.setItemText(0, _translate("Frame", "retrieve"))
        self.label_11.setText(_translate("Frame", "结果"))
        self.comboBox_19.setItemText(0, _translate("Frame", "first"))
        self.label_13.setText(_translate("Frame", "条件"))
        self.comboBox_20.setItemText(0, _translate("Frame", "start"))
        self.comboBox_21.setItemText(0, _translate("Frame", "goal"))
        self.comboBox_22.setItemText(0, _translate("Frame", "="))
        self.comboBox_23.setItemText(0, _translate("Frame", "IS"))
        self.comboBox_23.setItemText(1, _translate("Frame", "="))
        self.comboBox_23.setItemText(2, _translate("Frame", ">"))
        self.comboBox_23.setItemText(3, _translate("Frame", "<"))
        self.comboBox_23.setItemText(4, _translate("Frame", ">="))
        self.comboBox_23.setItemText(5, _translate("Frame", "<="))
        self.comboBox_24.setItemText(0, _translate("Frame", "="))
        self.label_27.setText(_translate("Frame", "过程知识"))
        __sortingEnabled = self.listWidget_6.isSortingEnabled()
        self.listWidget_6.setSortingEnabled(False)
        item = self.listWidget_6.item(0)
        item.setText(_translate("Frame", "start"))
        self.listWidget_6.setSortingEnabled(__sortingEnabled)
        self.label_28.setText(_translate("Frame", "模型参数"))
        self.label_29.setText(_translate("Frame", "陈述知识"))
        self.label_30.setText(_translate("Frame", "过程知识"))
        self.pushButton_7.setText(_translate("Frame", "+"))
        self.pushButton_8.setText(_translate("Frame", "-"))
        self.pushButton_9.setText(_translate("Frame", "-"))
        self.pushButton_10.setText(_translate("Frame", "+"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Frame", "参数调整"))
import resources_rc
